version: "3"
services:
    django:
        container_name: kpmg_django
        build:
            context: ./PatentAttorney_Django
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
    react:
        container_name: kpmg_react
        build:
            context: ./PatentAttorney_React
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - django